FROM opensearchproject/opensearch:1.3.20

WORKDIR /usr/share/opensearch/

COPY config/opendistroforelasticsearch /usr/share/opensearch/config
COPY bin/opendistroforelasticsearch/create-index.sh /usr/share/opensearch/create-index.sh

ENV http.port=19200
ENV plugins.security.disabled=true
ENV knn.algo_param.index_thread_qty=1
